name: CI Extreme

on:
  push:
    branches:
      - vic/extreme
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  check-compile-macos:
    name: Check macOS compilation
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Configure CI
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/ci-config.toml ./../.cargo/config.toml

      - name: Check that Cargo.lock is up to date
        run: |
          cargo update --locked --workspace

      - name: cargo clippy
        run: ./script/clippy

      - name: Run tests
        uses: ./.github/actions/run_tests

      - name: Build collab
        run: cargo build -p collab

      - name: Build other binaries and features
        run: |
          cargo build --workspace --bins --all-features
          cargo check -p gpui --features "macos-blade"
          cargo check -p workspace
          cargo build -p remote_server

      # Since the macOS runners are stateful, so we need to remove the config file to prevent potential bug.
      - name: Clean CI config file
        if: always()
        run: rm -rf ./../.cargo

  check-compile-linux:
    name: Check Linux compilation
    runs-on: ubuntu-latest
    steps:
      - name: Allow long git paths
        run: git config --global core.longpaths true

      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          clean: false

      - name: Cache dependencies
        uses: swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
        with:
          save-if: ${{ github.ref == 'refs/heads/vic/extreme' }}
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu


      - name: Install Linux dependencies
        run: ./script/linux

      - name: Configure CI
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/ci-config.toml ./../.cargo/config.toml

      - name: cargo clippy
        run: ./script/clippy

      - name: Run tests
        uses: ./.github/actions/run_tests

      - name: Build other binaries and features
        run: |
          cargo build -p zed
          cargo check -p workspace
        
        # cargo check -p gpui --examples

  check-compile-windows:
    name: Check Windows compilation
    runs-on: windows-latest
    steps:
      - name: Allow long git paths
        run: git config --global core.longpaths true

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-pc-windows-msvc

      - name: Configure CI
        run: |
          New-Item -ItemType Directory -Path "./../.cargo" -Force
          Copy-Item -Path "./.cargo/ci-config.toml" -Destination "./../.cargo/config.toml"

      - name: cargo clippy
        run: |
          .\script\clippy.ps1

      - name: Run tests
        uses: ./.github/actions/run_tests_windows

      - name: Build Zed
        run: cargo build

      - name: Clean CI config file
        if: always()
        run: Remove-Item -Recurse -Path "./../.cargo" -Force -ErrorAction SilentlyContinue

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [check-compile-macos, check-compile-linux, check-compile-windows]
    if: always()
    steps:
      - name: Check results
        run: |
          if [ "${{ needs.check-compile-macos.result }}" != "success" ] || \
             [ "${{ needs.check-compile-linux.result }}" != "success" ] || \
             [ "${{ needs.check-compile-windows.result }}" != "success" ]; then
            echo "One or more platforms failed compilation checks"
            exit 1
          else
            echo "All platforms compiled successfully"
          fi